services:
  student-service:
    mem_limit: 700m
    image: 'student-service:latest'
    container_name: student-service-container
    build:
      context: ./student-service
    ports:
      - "8181:8181"
    depends_on:
      - config-server
      - discovery-server
      - db
      # - rabbitmq
    environment:
      - spring.config.import=optional:configserver:http://config-server:8888/
      # add profile:
      - spring.profiles.active:dev
      - spring.cloud.config.profile:dev
      #Config DB:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://db:5432/meherguru
      - spring.datasource.username=meherguru
      - spring.datasource.password=password
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      # Eureka:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
      #- spring.zipkin.baseurl:http://zipkin-server:9411/
      # RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      # SPRING_RABBITMQ_HOST: rabbitmq
      # SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - campusConnect-network


  address-service:
    image: 'address-service:latest'
    container_name: address-service-container
    build:
      context: ./address-service
    mem_limit: 700m
    ports:
      - "8281:8281"
    depends_on:
      - config-server
      - discovery-server
      - db
      # - rabbitmq
    environment:
      - spring.config.import=optional:configserver:http://config-server:8888/
      # add profile:
      - spring.profiles.active:dev
      - spring.cloud.config.profile:dev
      #Config DB:
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://db:5432/meherguru
      - spring.datasource.username=meherguru
      - spring.datasource.password=password
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      # Eureka:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
      #- spring.zipkin.baseurl:http://zipkin-server:9411/

      # RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      # SPRING_RABBITMQ_HOST: rabbitmq
      # SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - campusConnect-network

  api-gateway:
    image: 'api-gateway:latest'
    container_name: api-gateway-container
    build:
      context: ./api-gateway
    mem_limit: 700m
    ports:
      - "8765:8765"
    depends_on:
      - config-server
      - discovery-server

      # restart: on-failure

      # - rabbitmq
    environment:
      - spring.config.import=optional:configserver:http://config-server:8888/
      # add profile:
      - spring.profiles.active:dev
      - spring.cloud.config.profile:dev
      # Eureka:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
      #- spring.zipkin.baseurl:http://zipkin-server:9411/

      #  RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      #  SPRING_RABBITMQ_HOST: rabbitmq
      #  SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - campusConnect-network


  discovery-server:
    image: 'discovery-server:latest'
    container_name: discovery-server-container
    build:
      context: ./eureka-discovery-server
    mem_limit: 700m
    depends_on:
      - config-server
    ports:
      - "8761:8761"

    environment:
      - spring.config.import=optional:configserver:http://config-server:8888/
      # add profile:
      - spring.profiles.active:dev
      - spring.cloud.config.profile:dev
    networks:
      - campusConnect-network

  config-server:
    image: 'config-server:latest'
    container_name: config-server-container
    build:
      context: ./config-server-university
    mem_limit: 700m
    ports:
      - "8888:8888"
    restart: on-failure
    environment:
      - spring.cloud.config.server.git.uri:https://github.com/meher12/university-config-repo.git
      #- spring.cloud.config.server.git.timeout:4
    networks:
      - campusConnect-network

  db:
    # container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: meherguru
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - campusConnect-network
    restart: unless-stopped

  pgadmin:
    # container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - campusConnect-network
    restart: unless-stopped

  #zipkin-server:
  #  image: openzipkin/zipkin:latest
  #  mem_limit: 300m
  #  ports:
  #    - "9411:9411"
    # environment:
    #   RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    # depends_on:
    #   - rabbitmq
  #  networks:
  #    - campusConnect-network
  #  restart: always #Restart if there is a problem starting up

networks:
  campusConnect-network:
  #driver: bridge

volumes:
  postgres:
  pgadmin: